server:
  port: 80

spring:
  application:
    name: service-gateway

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            maxAge: 3600

      discovery:
        locator:
          enabled: true

      routes:
        - id: service-common
          uri: lb://service-common
          predicates:
            - Path=/*/common/**
        - id: service-hospital
          uri: lb://service-hospital
          predicates:
            - Path=/*/hospital/**
        - id: service-user
          uri: lb://service-user
          predicates:
            - Path=/*/user/**

        - id: service-sms
          uri: lb://service-sms
          predicates:
            - Path=/*/sms/**
        - id: service-oss
          uri: lb://service-oss
          predicates:
              - Path=/*/oss/**
        - id: service-order
          uri: lb://service-order
          predicates:
              - Path=/*/order/**
        - id: service-task
          uri: lb://service-task
          predicates:
              - Path=/*/task/**
        - id: service-statistics
          uri: lb://service-statistics
          predicates:
              - Path=/*/statistics/**

admin:
  authorization: admin
