server:
  port: 8230

spring:
  application:
    name: service-user

  cloud:
    nacos:
      discovery:
        server-addr: nacos:8848

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql:3306/doctorarrival_user?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    username: root
    password: 123456

  data:
    redis:
      host: redis
      password: 123456

wx:
  open:
    app-id: <<your app-id>>
    app-secret: <<your app-secret>>
    redirect-uri: <<your redirect-uri>>
    site-origin: <<your site-origin>>
