server:
  port: 8250

spring:
  application:
    name: service-sms

  cloud:
    nacos:
      discovery:
        server-addr: <<nacos地址>>

  data:
    redis:
      host: <<redis地址>>
      password: <<redis密码>>

  rabbitmq:
    host: <<rabbitmq地址>>
    username: <<rabbitmq用户名>>
    password: <<rabbitmq密码>>

aliyun:
  sms:
    endpoint: <<your endpoint>>
    access-key-id: <<your access-key-id>>
    access-key-secret: <<your access-key-secret>>
    region: <<your region>>
    sign-name: <<your sign-name>>
    template-code-for-verification-code: <<your template-code-for-verification-code>>
    template-code-for-appointment-reminder: <<your template-code-for-appointment-reminder>>
