server:
  port: 8270

spring:
  application:
    name: service-order

  cloud:
    nacos:
      discovery:
        server-addr: nacos:8848

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql:3306/doctorarrival_order?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    username: root
    password: 123456

  rabbitmq:
    host: rabbitmq
    username: admin
    password: admin


pay:
  wx:
    merchant-id: <<商户号>>
    private-key-path: <<商户API私钥路径>>
    merchant-serial-number: <<商户证书序列号>>
    api-v3-key: <<商户APIV3密钥>>

  ali:
    server-url: <<支付宝网关地址>>
    app-id: <<支付宝应用ID>>
    private-key: <<应用私钥>>
    alipay-public-key: <<支付宝公钥>>
    site-origin: <<站点域名>>
