server:
  port: 8280

spring:
  application:
    name: service-task

  cloud:
    nacos:
      discovery:
        server-addr: <<nacos地址>>

  rabbitmq:
    host: <<rabbitmq地址>>
    username: <<rabbitmq用户名>>
    password: <<rabbitmq密码>>
