server:
  port: 8280

spring:
  application:
    name: service-task

  cloud:
    nacos:
      discovery:
        server-addr: nacos:8848

  rabbitmq:
    host: rabbitmq
    username: admin
    password: admin
