server:
  port: 8220

spring:
  application:
    name: service-hospital
  profiles:
    active: dev

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://<<数据库地址>>/doctorarrival_hospital?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    username: <<数据库用户名>>
    password: <<数据库密码>>

  data:
    redis:
      host: <<redis地址>>
      password: <<redis密码>>
