server:
  port: 8220

spring:
  application:
    name: service-hospital

  cloud:
    nacos:
      discovery:
        server-addr: nacos:8848

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql:3306/doctorarrival_hospital?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    username: root
    password: 123456

  data:
    redis:
      host: redis
      password: 123456

    mongodb:
      host: mongodb
      database: doctorarrival_hospital
      username: admin
      password: 123456
      authentication-database: admin

  rabbitmq:
    host: rabbitmq
    username: admin
    password: admin
