server:
  port: 8999

spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

doctorarrival:
  serverUrl: http://service-gateway/api/hospital/side
  hospitalCode: 8999
  privateKeyLocation: config/8999.key
